### ISSUE TITLE
Can't login ui, Login failed: username or password may be incorrect

### ISSUE THREAD

**Issue by kylinda** [geldata/gel-ui#419]
Hi,

The url is "http://10.11.11.11:5656/ui/_login",
I tried create a instance, and update admin's password. but did not work.

podman run \
  --name gel \
  -e GEL_SERVER_HOST=10.11.11.11 \
  -e GEL_SERVER_SECURITY=insecure_dev_mode \
  -e GEL_SERVER_TLS_CERT_MODE=generate_self_signed \
  -e GEL_SERVER_ADMIN_UI=enabled \
  -e GEL_SERVER_PASSWORD=123456 \
  -v /media/data/gel-06:/var/lib/gel/data \
  -p 5656:5656 \
  -d geldata/gel

![Image](https://github.com/user-attachments/assets/99a1b9eb-b9e3-4549-9f17-aa068084da81)

Please help, thanks.

**Comment by NelsonDane** [comment]
```yaml
edgedb:
    image: edgedb/edgedb:latest
    container_name: edgedb
    restart: always
    environment:
      #- GEL_SERVER_SECURITY=insecure_dev_mode
      - GEL_SERVER_ADMIN_UI=enabled
      - GEL_SERVER_BIND_ADDRESS=0.0.0.0
      - GEL_SERVER_USER=edgedb
      - GEL_SERVER_PASSWORD=edgedb
      - GEL_SERVER_TLS_CERT_MODE=generate_self_signed
    volumes:
      - ./config/edgedb:/var/lib/edgedb/data
      - ./dbschema:/dbschema
    ports:
      - 5656:5656
  ```
Same issue here, can't for the life of me figure out how to login and access my data. I would expect to be able to get into the Web UI via the env vars, but that's not the case. I even ran `ALTER ROLE edgedb SET password := "password";` as suggested [here](https://github.com/geldata/gel-ui/issues/391#issuecomment-2699514479) for both edgedb and admin users, and still can't get in with either.
